[config]
schemaVersion = "0.6.2"

[package]
namespace = "deB"
name = "WILDCARDStuff"
versionNumber = "0.6.2"
description = "Adds content based on YouTube org WILDCARD!"
websiteUrl = "https://github.com/TheDebbyCase/LCWildCardMod"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.16.2"
Rune580-LethalCompany_InputUtils = "0.7.7"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "."

[[build.copy]]
source = "./Builds/netstandard2.1/LCWildCardMod.dll"
target = "BepInEx/plugins/WildCardMod/LCWildCardMod.dll"

[[build.copy]]
source = "./Builds/wildcardmod"
target = "BepInEx/plugins/WildCardMod/wildcardmod"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[publish]
communities = ["lethal-company"]
[publish.categories]
lethal-company = ["bepinex", "mods", "items", "serverside"]


